// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fir_fir_Pipeline_Shift_Accum_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_TVALID,
        x_TDATA,
        x_TREADY,
        acc_out,
        acc_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   x_TVALID;
input  [31:0] x_TDATA;
output   x_TREADY;
output  [31:0] acc_out;
output   acc_out_ap_vld;

reg ap_idle;
reg x_TREADY;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire   [0:0] tmp_fu_828_p3;
wire   [0:0] icmp_ln25_fu_841_p2;
reg    ap_predicate_op204_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] firCoeff_address0;
reg    firCoeff_ce0;
wire   [11:0] firCoeff_q0;
reg   [31:0] fir_int_int_shift_reg;
reg   [31:0] fir_int_int_shift_reg_1;
reg   [31:0] fir_int_int_shift_reg_2;
reg   [31:0] fir_int_int_shift_reg_3;
reg   [31:0] fir_int_int_shift_reg_4;
reg   [31:0] fir_int_int_shift_reg_5;
reg   [31:0] fir_int_int_shift_reg_6;
reg   [31:0] fir_int_int_shift_reg_7;
reg   [31:0] fir_int_int_shift_reg_8;
reg   [31:0] fir_int_int_shift_reg_9;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_10;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_11;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_12;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_13;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_14;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_15;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_16;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_17;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_18;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_19;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_20;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_21;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_22;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_23;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_24;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_25;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_26;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_27;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_28;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_29;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_30;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_31;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_32;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_33;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_34;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_35;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_36;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_37;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_38;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_39;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_40;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_41;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_42;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_43;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_44;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_45;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_46;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_47;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_48;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_49;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_50;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_51;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_52;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_53;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_54;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_55;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_56;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_57;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_58;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_59;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_60;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_61;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_62;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_63;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_64;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_65;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_66;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_67;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_68;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_69;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_70;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_71;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_72;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_73;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_74;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_75;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_76;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_77;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_78;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_79;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_80;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_81;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_82;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_83;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_84;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_85;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_86;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_87;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_88;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_89;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_90;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_91;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_92;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_93;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_94;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_95;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_96;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_97;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_98;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_99;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_100;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_101;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_102;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_103;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_104;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_105;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_106;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_107;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_108;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_109;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_110;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_111;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_112;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_113;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_114;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_115;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_116;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_117;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_118;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_119;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_120;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_121;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_122;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_123;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_124;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_125;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_126;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_127;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_128;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_129;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_130;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_131;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_132;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_133;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_134;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_135;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_136;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_137;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_138;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_139;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_140;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_141;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_142;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_143;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_144;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_145;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_146;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_147;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_148;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_149;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_150;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_151;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_152;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_153;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_154;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_155;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_156;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_157;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_158;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_159;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_160;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_161;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_162;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_163;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_164;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_165;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_166;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_167;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_168;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_169;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_170;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_171;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_172;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_173;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_174;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_175;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_176;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_177;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_178;
reg   [31:0] p_ZZ3firPiS_E9shift_reg_179;
wire    x_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_reg_3076;
reg   [0:0] tmp_reg_3076_pp0_iter1_reg;
reg   [0:0] icmp_ln25_reg_3080;
wire   [7:0] trunc_ln29_fu_847_p1;
reg   [7:0] trunc_ln29_reg_3084;
wire   [31:0] data_1_fu_1588_p183;
reg  signed [11:0] firCoeff_load_reg_3104;
wire   [31:0] mul_ln32_fu_3038_p2;
reg   [31:0] mul_ln32_reg_3109;
wire  signed [31:0] ap_phi_reg_pp0_iter0_data_2_reg_806;
reg  signed [31:0] ap_phi_reg_pp0_iter1_data_2_reg_806;
reg  signed [31:0] ap_phi_reg_pp0_iter2_data_2_reg_806;
wire   [63:0] i_cast_fu_836_p1;
reg   [31:0] acc_fu_772;
wire   [31:0] acc_1_fu_3047_p2;
wire    ap_loop_init;
reg   [8:0] i_fu_776;
wire   [8:0] add_ln21_fu_857_p2;
reg   [8:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [3:0] frp_pipeline_valid_U_valid_out;
wire   [2:0] frp_pipeline_valid_U_num_valid_datasets;
reg    ap_condition_frp_pvb_no_fwd_prs;
wire    ap_condition_frp_pvb_no_bkwd_prs;
reg    ap_condition_frp_pvb_pf_start;
reg    ap_frp_vld_in;
reg    frp_pipeline_valid_U_exitcond;
reg    ap_condition_1710;
reg    ap_condition_1715;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 fir_int_int_shift_reg = 32'd0;
#0 fir_int_int_shift_reg_1 = 32'd0;
#0 fir_int_int_shift_reg_2 = 32'd0;
#0 fir_int_int_shift_reg_3 = 32'd0;
#0 fir_int_int_shift_reg_4 = 32'd0;
#0 fir_int_int_shift_reg_5 = 32'd0;
#0 fir_int_int_shift_reg_6 = 32'd0;
#0 fir_int_int_shift_reg_7 = 32'd0;
#0 fir_int_int_shift_reg_8 = 32'd0;
#0 fir_int_int_shift_reg_9 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_10 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_11 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_12 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_13 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_14 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_15 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_16 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_17 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_18 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_19 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_20 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_21 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_22 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_23 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_24 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_25 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_26 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_27 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_28 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_29 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_30 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_31 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_32 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_33 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_34 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_35 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_36 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_37 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_38 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_39 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_40 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_41 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_42 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_43 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_44 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_45 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_46 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_47 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_48 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_49 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_50 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_51 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_52 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_53 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_54 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_55 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_56 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_57 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_58 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_59 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_60 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_61 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_62 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_63 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_64 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_65 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_66 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_67 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_68 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_69 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_70 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_71 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_72 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_73 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_74 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_75 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_76 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_77 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_78 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_79 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_80 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_81 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_82 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_83 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_84 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_85 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_86 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_87 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_88 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_89 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_90 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_91 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_92 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_93 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_94 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_95 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_96 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_97 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_98 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_99 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_100 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_101 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_102 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_103 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_104 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_105 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_106 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_107 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_108 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_109 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_110 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_111 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_112 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_113 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_114 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_115 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_116 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_117 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_118 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_119 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_120 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_121 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_122 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_123 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_124 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_125 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_126 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_127 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_128 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_129 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_130 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_131 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_132 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_133 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_134 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_135 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_136 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_137 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_138 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_139 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_140 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_141 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_142 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_143 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_144 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_145 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_146 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_147 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_148 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_149 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_150 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_151 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_152 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_153 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_154 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_155 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_156 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_157 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_158 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_159 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_160 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_161 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_162 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_163 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_164 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_165 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_166 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_167 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_168 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_169 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_170 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_171 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_172 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_173 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_174 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_175 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_176 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_177 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_178 = 32'd0;
#0 p_ZZ3firPiS_E9shift_reg_179 = 32'd0;
#0 ap_done_reg = 1'b0;
end

fir_fir_Pipeline_Shift_Accum_Loop_firCoeff_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 181 ),
    .AddressWidth( 8 ))
firCoeff_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(firCoeff_address0),
    .ce0(firCoeff_ce0),
    .q0(firCoeff_q0)
);

fir_mux_1818_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 32 ),
    .din65_WIDTH( 32 ),
    .din66_WIDTH( 32 ),
    .din67_WIDTH( 32 ),
    .din68_WIDTH( 32 ),
    .din69_WIDTH( 32 ),
    .din70_WIDTH( 32 ),
    .din71_WIDTH( 32 ),
    .din72_WIDTH( 32 ),
    .din73_WIDTH( 32 ),
    .din74_WIDTH( 32 ),
    .din75_WIDTH( 32 ),
    .din76_WIDTH( 32 ),
    .din77_WIDTH( 32 ),
    .din78_WIDTH( 32 ),
    .din79_WIDTH( 32 ),
    .din80_WIDTH( 32 ),
    .din81_WIDTH( 32 ),
    .din82_WIDTH( 32 ),
    .din83_WIDTH( 32 ),
    .din84_WIDTH( 32 ),
    .din85_WIDTH( 32 ),
    .din86_WIDTH( 32 ),
    .din87_WIDTH( 32 ),
    .din88_WIDTH( 32 ),
    .din89_WIDTH( 32 ),
    .din90_WIDTH( 32 ),
    .din91_WIDTH( 32 ),
    .din92_WIDTH( 32 ),
    .din93_WIDTH( 32 ),
    .din94_WIDTH( 32 ),
    .din95_WIDTH( 32 ),
    .din96_WIDTH( 32 ),
    .din97_WIDTH( 32 ),
    .din98_WIDTH( 32 ),
    .din99_WIDTH( 32 ),
    .din100_WIDTH( 32 ),
    .din101_WIDTH( 32 ),
    .din102_WIDTH( 32 ),
    .din103_WIDTH( 32 ),
    .din104_WIDTH( 32 ),
    .din105_WIDTH( 32 ),
    .din106_WIDTH( 32 ),
    .din107_WIDTH( 32 ),
    .din108_WIDTH( 32 ),
    .din109_WIDTH( 32 ),
    .din110_WIDTH( 32 ),
    .din111_WIDTH( 32 ),
    .din112_WIDTH( 32 ),
    .din113_WIDTH( 32 ),
    .din114_WIDTH( 32 ),
    .din115_WIDTH( 32 ),
    .din116_WIDTH( 32 ),
    .din117_WIDTH( 32 ),
    .din118_WIDTH( 32 ),
    .din119_WIDTH( 32 ),
    .din120_WIDTH( 32 ),
    .din121_WIDTH( 32 ),
    .din122_WIDTH( 32 ),
    .din123_WIDTH( 32 ),
    .din124_WIDTH( 32 ),
    .din125_WIDTH( 32 ),
    .din126_WIDTH( 32 ),
    .din127_WIDTH( 32 ),
    .din128_WIDTH( 32 ),
    .din129_WIDTH( 32 ),
    .din130_WIDTH( 32 ),
    .din131_WIDTH( 32 ),
    .din132_WIDTH( 32 ),
    .din133_WIDTH( 32 ),
    .din134_WIDTH( 32 ),
    .din135_WIDTH( 32 ),
    .din136_WIDTH( 32 ),
    .din137_WIDTH( 32 ),
    .din138_WIDTH( 32 ),
    .din139_WIDTH( 32 ),
    .din140_WIDTH( 32 ),
    .din141_WIDTH( 32 ),
    .din142_WIDTH( 32 ),
    .din143_WIDTH( 32 ),
    .din144_WIDTH( 32 ),
    .din145_WIDTH( 32 ),
    .din146_WIDTH( 32 ),
    .din147_WIDTH( 32 ),
    .din148_WIDTH( 32 ),
    .din149_WIDTH( 32 ),
    .din150_WIDTH( 32 ),
    .din151_WIDTH( 32 ),
    .din152_WIDTH( 32 ),
    .din153_WIDTH( 32 ),
    .din154_WIDTH( 32 ),
    .din155_WIDTH( 32 ),
    .din156_WIDTH( 32 ),
    .din157_WIDTH( 32 ),
    .din158_WIDTH( 32 ),
    .din159_WIDTH( 32 ),
    .din160_WIDTH( 32 ),
    .din161_WIDTH( 32 ),
    .din162_WIDTH( 32 ),
    .din163_WIDTH( 32 ),
    .din164_WIDTH( 32 ),
    .din165_WIDTH( 32 ),
    .din166_WIDTH( 32 ),
    .din167_WIDTH( 32 ),
    .din168_WIDTH( 32 ),
    .din169_WIDTH( 32 ),
    .din170_WIDTH( 32 ),
    .din171_WIDTH( 32 ),
    .din172_WIDTH( 32 ),
    .din173_WIDTH( 32 ),
    .din174_WIDTH( 32 ),
    .din175_WIDTH( 32 ),
    .din176_WIDTH( 32 ),
    .din177_WIDTH( 32 ),
    .din178_WIDTH( 32 ),
    .din179_WIDTH( 32 ),
    .din180_WIDTH( 32 ),
    .din181_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mux_1818_32_1_1_U1(
    .din0(32'd0),
    .din1(fir_int_int_shift_reg),
    .din2(fir_int_int_shift_reg_1),
    .din3(fir_int_int_shift_reg_2),
    .din4(fir_int_int_shift_reg_3),
    .din5(fir_int_int_shift_reg_4),
    .din6(fir_int_int_shift_reg_5),
    .din7(fir_int_int_shift_reg_6),
    .din8(fir_int_int_shift_reg_7),
    .din9(fir_int_int_shift_reg_8),
    .din10(fir_int_int_shift_reg_9),
    .din11(p_ZZ3firPiS_E9shift_reg_10),
    .din12(p_ZZ3firPiS_E9shift_reg_11),
    .din13(p_ZZ3firPiS_E9shift_reg_12),
    .din14(p_ZZ3firPiS_E9shift_reg_13),
    .din15(p_ZZ3firPiS_E9shift_reg_14),
    .din16(p_ZZ3firPiS_E9shift_reg_15),
    .din17(p_ZZ3firPiS_E9shift_reg_16),
    .din18(p_ZZ3firPiS_E9shift_reg_17),
    .din19(p_ZZ3firPiS_E9shift_reg_18),
    .din20(p_ZZ3firPiS_E9shift_reg_19),
    .din21(p_ZZ3firPiS_E9shift_reg_20),
    .din22(p_ZZ3firPiS_E9shift_reg_21),
    .din23(p_ZZ3firPiS_E9shift_reg_22),
    .din24(p_ZZ3firPiS_E9shift_reg_23),
    .din25(p_ZZ3firPiS_E9shift_reg_24),
    .din26(p_ZZ3firPiS_E9shift_reg_25),
    .din27(p_ZZ3firPiS_E9shift_reg_26),
    .din28(p_ZZ3firPiS_E9shift_reg_27),
    .din29(p_ZZ3firPiS_E9shift_reg_28),
    .din30(p_ZZ3firPiS_E9shift_reg_29),
    .din31(p_ZZ3firPiS_E9shift_reg_30),
    .din32(p_ZZ3firPiS_E9shift_reg_31),
    .din33(p_ZZ3firPiS_E9shift_reg_32),
    .din34(p_ZZ3firPiS_E9shift_reg_33),
    .din35(p_ZZ3firPiS_E9shift_reg_34),
    .din36(p_ZZ3firPiS_E9shift_reg_35),
    .din37(p_ZZ3firPiS_E9shift_reg_36),
    .din38(p_ZZ3firPiS_E9shift_reg_37),
    .din39(p_ZZ3firPiS_E9shift_reg_38),
    .din40(p_ZZ3firPiS_E9shift_reg_39),
    .din41(p_ZZ3firPiS_E9shift_reg_40),
    .din42(p_ZZ3firPiS_E9shift_reg_41),
    .din43(p_ZZ3firPiS_E9shift_reg_42),
    .din44(p_ZZ3firPiS_E9shift_reg_43),
    .din45(p_ZZ3firPiS_E9shift_reg_44),
    .din46(p_ZZ3firPiS_E9shift_reg_45),
    .din47(p_ZZ3firPiS_E9shift_reg_46),
    .din48(p_ZZ3firPiS_E9shift_reg_47),
    .din49(p_ZZ3firPiS_E9shift_reg_48),
    .din50(p_ZZ3firPiS_E9shift_reg_49),
    .din51(p_ZZ3firPiS_E9shift_reg_50),
    .din52(p_ZZ3firPiS_E9shift_reg_51),
    .din53(p_ZZ3firPiS_E9shift_reg_52),
    .din54(p_ZZ3firPiS_E9shift_reg_53),
    .din55(p_ZZ3firPiS_E9shift_reg_54),
    .din56(p_ZZ3firPiS_E9shift_reg_55),
    .din57(p_ZZ3firPiS_E9shift_reg_56),
    .din58(p_ZZ3firPiS_E9shift_reg_57),
    .din59(p_ZZ3firPiS_E9shift_reg_58),
    .din60(p_ZZ3firPiS_E9shift_reg_59),
    .din61(p_ZZ3firPiS_E9shift_reg_60),
    .din62(p_ZZ3firPiS_E9shift_reg_61),
    .din63(p_ZZ3firPiS_E9shift_reg_62),
    .din64(p_ZZ3firPiS_E9shift_reg_63),
    .din65(p_ZZ3firPiS_E9shift_reg_64),
    .din66(p_ZZ3firPiS_E9shift_reg_65),
    .din67(p_ZZ3firPiS_E9shift_reg_66),
    .din68(p_ZZ3firPiS_E9shift_reg_67),
    .din69(p_ZZ3firPiS_E9shift_reg_68),
    .din70(p_ZZ3firPiS_E9shift_reg_69),
    .din71(p_ZZ3firPiS_E9shift_reg_70),
    .din72(p_ZZ3firPiS_E9shift_reg_71),
    .din73(p_ZZ3firPiS_E9shift_reg_72),
    .din74(p_ZZ3firPiS_E9shift_reg_73),
    .din75(p_ZZ3firPiS_E9shift_reg_74),
    .din76(p_ZZ3firPiS_E9shift_reg_75),
    .din77(p_ZZ3firPiS_E9shift_reg_76),
    .din78(p_ZZ3firPiS_E9shift_reg_77),
    .din79(p_ZZ3firPiS_E9shift_reg_78),
    .din80(p_ZZ3firPiS_E9shift_reg_79),
    .din81(p_ZZ3firPiS_E9shift_reg_80),
    .din82(p_ZZ3firPiS_E9shift_reg_81),
    .din83(p_ZZ3firPiS_E9shift_reg_82),
    .din84(p_ZZ3firPiS_E9shift_reg_83),
    .din85(p_ZZ3firPiS_E9shift_reg_84),
    .din86(p_ZZ3firPiS_E9shift_reg_85),
    .din87(p_ZZ3firPiS_E9shift_reg_86),
    .din88(p_ZZ3firPiS_E9shift_reg_87),
    .din89(p_ZZ3firPiS_E9shift_reg_88),
    .din90(p_ZZ3firPiS_E9shift_reg_89),
    .din91(p_ZZ3firPiS_E9shift_reg_90),
    .din92(p_ZZ3firPiS_E9shift_reg_91),
    .din93(p_ZZ3firPiS_E9shift_reg_92),
    .din94(p_ZZ3firPiS_E9shift_reg_93),
    .din95(p_ZZ3firPiS_E9shift_reg_94),
    .din96(p_ZZ3firPiS_E9shift_reg_95),
    .din97(p_ZZ3firPiS_E9shift_reg_96),
    .din98(p_ZZ3firPiS_E9shift_reg_97),
    .din99(p_ZZ3firPiS_E9shift_reg_98),
    .din100(p_ZZ3firPiS_E9shift_reg_99),
    .din101(p_ZZ3firPiS_E9shift_reg_100),
    .din102(p_ZZ3firPiS_E9shift_reg_101),
    .din103(p_ZZ3firPiS_E9shift_reg_102),
    .din104(p_ZZ3firPiS_E9shift_reg_103),
    .din105(p_ZZ3firPiS_E9shift_reg_104),
    .din106(p_ZZ3firPiS_E9shift_reg_105),
    .din107(p_ZZ3firPiS_E9shift_reg_106),
    .din108(p_ZZ3firPiS_E9shift_reg_107),
    .din109(p_ZZ3firPiS_E9shift_reg_108),
    .din110(p_ZZ3firPiS_E9shift_reg_109),
    .din111(p_ZZ3firPiS_E9shift_reg_110),
    .din112(p_ZZ3firPiS_E9shift_reg_111),
    .din113(p_ZZ3firPiS_E9shift_reg_112),
    .din114(p_ZZ3firPiS_E9shift_reg_113),
    .din115(p_ZZ3firPiS_E9shift_reg_114),
    .din116(p_ZZ3firPiS_E9shift_reg_115),
    .din117(p_ZZ3firPiS_E9shift_reg_116),
    .din118(p_ZZ3firPiS_E9shift_reg_117),
    .din119(p_ZZ3firPiS_E9shift_reg_118),
    .din120(p_ZZ3firPiS_E9shift_reg_119),
    .din121(p_ZZ3firPiS_E9shift_reg_120),
    .din122(p_ZZ3firPiS_E9shift_reg_121),
    .din123(p_ZZ3firPiS_E9shift_reg_122),
    .din124(p_ZZ3firPiS_E9shift_reg_123),
    .din125(p_ZZ3firPiS_E9shift_reg_124),
    .din126(p_ZZ3firPiS_E9shift_reg_125),
    .din127(p_ZZ3firPiS_E9shift_reg_126),
    .din128(p_ZZ3firPiS_E9shift_reg_127),
    .din129(p_ZZ3firPiS_E9shift_reg_128),
    .din130(p_ZZ3firPiS_E9shift_reg_129),
    .din131(p_ZZ3firPiS_E9shift_reg_130),
    .din132(p_ZZ3firPiS_E9shift_reg_131),
    .din133(p_ZZ3firPiS_E9shift_reg_132),
    .din134(p_ZZ3firPiS_E9shift_reg_133),
    .din135(p_ZZ3firPiS_E9shift_reg_134),
    .din136(p_ZZ3firPiS_E9shift_reg_135),
    .din137(p_ZZ3firPiS_E9shift_reg_136),
    .din138(p_ZZ3firPiS_E9shift_reg_137),
    .din139(p_ZZ3firPiS_E9shift_reg_138),
    .din140(p_ZZ3firPiS_E9shift_reg_139),
    .din141(p_ZZ3firPiS_E9shift_reg_140),
    .din142(p_ZZ3firPiS_E9shift_reg_141),
    .din143(p_ZZ3firPiS_E9shift_reg_142),
    .din144(p_ZZ3firPiS_E9shift_reg_143),
    .din145(p_ZZ3firPiS_E9shift_reg_144),
    .din146(p_ZZ3firPiS_E9shift_reg_145),
    .din147(p_ZZ3firPiS_E9shift_reg_146),
    .din148(p_ZZ3firPiS_E9shift_reg_147),
    .din149(p_ZZ3firPiS_E9shift_reg_148),
    .din150(p_ZZ3firPiS_E9shift_reg_149),
    .din151(p_ZZ3firPiS_E9shift_reg_150),
    .din152(p_ZZ3firPiS_E9shift_reg_151),
    .din153(p_ZZ3firPiS_E9shift_reg_152),
    .din154(p_ZZ3firPiS_E9shift_reg_153),
    .din155(p_ZZ3firPiS_E9shift_reg_154),
    .din156(p_ZZ3firPiS_E9shift_reg_155),
    .din157(p_ZZ3firPiS_E9shift_reg_156),
    .din158(p_ZZ3firPiS_E9shift_reg_157),
    .din159(p_ZZ3firPiS_E9shift_reg_158),
    .din160(p_ZZ3firPiS_E9shift_reg_159),
    .din161(p_ZZ3firPiS_E9shift_reg_160),
    .din162(p_ZZ3firPiS_E9shift_reg_161),
    .din163(p_ZZ3firPiS_E9shift_reg_162),
    .din164(p_ZZ3firPiS_E9shift_reg_163),
    .din165(p_ZZ3firPiS_E9shift_reg_164),
    .din166(p_ZZ3firPiS_E9shift_reg_165),
    .din167(p_ZZ3firPiS_E9shift_reg_166),
    .din168(p_ZZ3firPiS_E9shift_reg_167),
    .din169(p_ZZ3firPiS_E9shift_reg_168),
    .din170(p_ZZ3firPiS_E9shift_reg_169),
    .din171(p_ZZ3firPiS_E9shift_reg_170),
    .din172(p_ZZ3firPiS_E9shift_reg_171),
    .din173(p_ZZ3firPiS_E9shift_reg_172),
    .din174(p_ZZ3firPiS_E9shift_reg_173),
    .din175(p_ZZ3firPiS_E9shift_reg_174),
    .din176(p_ZZ3firPiS_E9shift_reg_175),
    .din177(p_ZZ3firPiS_E9shift_reg_176),
    .din178(p_ZZ3firPiS_E9shift_reg_177),
    .din179(p_ZZ3firPiS_E9shift_reg_178),
    .din180(p_ZZ3firPiS_E9shift_reg_179),
    .din181(trunc_ln29_reg_3084),
    .dout(data_1_fu_1588_p183)
);

fir_mul_12s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_12s_32s_32_1_1_U2(
    .din0(firCoeff_load_reg_3104),
    .din1(ap_phi_reg_pp0_iter2_data_2_reg_806),
    .dout(mul_ln32_fu_3038_p2)
);

fir_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

fir_frp_pipeline_valid #(
    .PipelineLatency( 4 ),
    .PipelineII( 1 ),
    .CeilLog2Stages( 2 ),
    .ExitLatency( 0 ))
frp_pipeline_valid_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .valid_in(ap_frp_vld_in),
    .exitcond(frp_pipeline_valid_U_exitcond),
    .valid_out(frp_pipeline_valid_U_valid_out),
    .num_valid_datasets(frp_pipeline_valid_U_num_valid_datasets)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            acc_fu_772 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            acc_fu_772 <= acc_1_fu_3047_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1)) begin
        if ((1'b1 == ap_condition_1710)) begin
            ap_phi_reg_pp0_iter1_data_2_reg_806 <= x_TDATA;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_phi_reg_pp0_iter1_data_2_reg_806 <= ap_phi_reg_pp0_iter0_data_2_reg_806;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1)) begin
        if ((1'b1 == ap_condition_1715)) begin
            ap_phi_reg_pp0_iter2_data_2_reg_806 <= data_1_fu_1588_p183;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_phi_reg_pp0_iter2_data_2_reg_806 <= ap_phi_reg_pp0_iter1_data_2_reg_806;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_fu_841_p2 == 1'd1) & (tmp_fu_828_p3 == 1'd0)))) begin
        fir_int_int_shift_reg <= x_TDATA;
    end else if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd0) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_fu_828_p3 == 1'd0)))) begin
        i_fu_776 <= add_ln21_fu_857_p2;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        i_fu_776 <= 9'd180;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        firCoeff_load_reg_3104 <= firCoeff_q0;
        tmp_reg_3076 <= ap_sig_allocacmp_i_1[32'd8];
        tmp_reg_3076_pp0_iter1_reg <= tmp_reg_3076;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd1) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_1 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd2) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_2 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd3) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_3 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd4) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_4 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd5) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_5 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd6) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_6 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd7) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_7 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd8) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_8 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd9) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        fir_int_int_shift_reg_9 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_fu_828_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln25_reg_3080 <= icmp_ln25_fu_841_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        mul_ln32_reg_3109 <= mul_ln32_fu_3038_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd10) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_10 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd100) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_100 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd101) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_101 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd102) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_102 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd103) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_103 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd104) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_104 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd105) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_105 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd106) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_106 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd107) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_107 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd108) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_108 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd109) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_109 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd11) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_11 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd110) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_110 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd111) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_111 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd112) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_112 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd113) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_113 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd114) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_114 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd115) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_115 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd116) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_116 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd117) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_117 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd118) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_118 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd119) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_119 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd12) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_12 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd120) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_120 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd121) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_121 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd122) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_122 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd123) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_123 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd124) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_124 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd125) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_125 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd126) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_126 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd127) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_127 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd128) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_128 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd129) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_129 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd13) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_13 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd130) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_130 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd131) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_131 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd132) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_132 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd133) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_133 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd134) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_134 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd135) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_135 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd136) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_136 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd137) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_137 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd138) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_138 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd139) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_139 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd14) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_14 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd140) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_140 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd141) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_141 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd142) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_142 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd143) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_143 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd144) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_144 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd145) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_145 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd146) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_146 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd147) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_147 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd148) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_148 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd149) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_149 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd15) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_15 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd150) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_150 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd151) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_151 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd152) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_152 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd153) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_153 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd154) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_154 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd155) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_155 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd156) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_156 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd157) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_157 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd158) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_158 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd159) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_159 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd16) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_16 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd160) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_160 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd161) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_161 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd162) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_162 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd163) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_163 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd164) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_164 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd165) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_165 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd166) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_166 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd167) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_167 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd168) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_168 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd169) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_169 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd17) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_17 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd170) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_170 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd171) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_171 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd172) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_172 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd173) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_173 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd174) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_174 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd175) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_175 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd176) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_176 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd177) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_177 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd178) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_178 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd179) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_179 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd18) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_18 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd19) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_19 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd20) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_20 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd21) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_21 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd22) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_22 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd23) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_23 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd24) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_24 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd25) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_25 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd26) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_26 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd27) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_27 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd28) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_28 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd29) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_29 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd30) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_30 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd31) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_31 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd32) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_32 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd33) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_33 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd34) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_34 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd35) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_35 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd36) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_36 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd37) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_37 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd38) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_38 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd39) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_39 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd40) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_40 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd41) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_41 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd42) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_42 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd43) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_43 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd44) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_44 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd45) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_45 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd46) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_46 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd47) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_47 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd48) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_48 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd49) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_49 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd50) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_50 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd51) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_51 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd52) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_52 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd53) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_53 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd54) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_54 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd55) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_55 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd56) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_56 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd57) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_57 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd58) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_58 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd59) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_59 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd60) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_60 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd61) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_61 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd62) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_62 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd63) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_63 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd64) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_64 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd65) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_65 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd66) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_66 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd67) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_67 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd68) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_68 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd69) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_69 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd70) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_70 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd71) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_71 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd72) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_72 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd73) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_73 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd74) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_74 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd75) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_75 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd76) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_76 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd77) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_77 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd78) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_78 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd79) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_79 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd80) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_80 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd81) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_81 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd82) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_82 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd83) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_83 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd84) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_84 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd85) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_85 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd86) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_86 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd87) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_87 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd88) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_88 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd89) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_89 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd90) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_90 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd91) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_91 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd92) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_92 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd93) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_93 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd94) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_94 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd95) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_95 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd96) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_96 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd97) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_97 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd98) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_98 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln29_reg_3084 == 8'd99) & (icmp_ln25_reg_3080 == 1'd0)))) begin
        p_ZZ3firPiS_E9shift_reg_99 <= data_1_fu_1588_p183;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_fu_841_p2 == 1'd0) & (tmp_fu_828_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln29_reg_3084 <= trunc_ln29_fu_847_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_3076_pp0_iter1_reg == 1'd1))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_subdone) & (tmp_fu_828_p3 == 1'd1)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[2'd1] == 1'b1)) begin
        ap_enable_reg_pp0_iter1 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter1 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[2'd2] == 1'b1)) begin
        ap_enable_reg_pp0_iter2 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter2 = 1'b0;
    end
end

always @ (*) begin
    if ((frp_pipeline_valid_U_valid_out[2'd3] == 1'b1)) begin
        ap_enable_reg_pp0_iter3 = 1'b1;
    end else begin
        ap_enable_reg_pp0_iter3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_frp_pvb_pf_start) & (1'b1 == ap_condition_frp_pvb_no_bkwd_prs) & (1'b1 == ap_condition_frp_pvb_no_fwd_prs))) begin
        ap_frp_vld_in = 1'b1;
    end else begin
        ap_frp_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (frp_pipeline_valid_U_valid_out[2'd0] == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 9'd180;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_776;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (frp_pipeline_valid_U_valid_out[2'd0] == 1'b1))) begin
        firCoeff_ce0 = 1'b1;
    end else begin
        firCoeff_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_828_p3 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        frp_pipeline_valid_U_exitcond = 1'b1;
    end else begin
        frp_pipeline_valid_U_exitcond = 1'b0;
    end
end

always @ (*) begin
    if (((frp_pipeline_valid_U_valid_out[2'd0] == 1'b1) & ((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op204_read_state1 == 1'b1)))) begin
        x_TREADY = 1'b1;
    end else begin
        x_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_3047_p2 = (mul_ln32_reg_3109 + acc_fu_772);

assign acc_out = acc_fu_772;

assign add_ln21_fu_857_p2 = ($signed(ap_sig_allocacmp_i_1) + $signed(9'd511));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = 1'b0;

assign ap_block_pp0_stage0_01001 = 1'b0;

assign ap_block_pp0_stage0_11001 = 1'b0;

assign ap_block_pp0_stage0_subdone = 1'b0;

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op204_read_state1 == 1'b1) & (1'b1 == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1710 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_fu_841_p2 == 1'd1) & (tmp_fu_828_p3 == 1'd0));
end

always @ (*) begin
    ap_condition_1715 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln25_reg_3080 == 1'd0) & (tmp_reg_3076 == 1'd0));
end

assign ap_condition_frp_pvb_no_bkwd_prs = (1'b1 == 1'b1);

always @ (*) begin
    ap_condition_frp_pvb_no_fwd_prs = ~((ap_predicate_op204_read_state1 == 1'b1) & (x_TVALID == 1'b0));
end

always @ (*) begin
    ap_condition_frp_pvb_pf_start = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_data_2_reg_806 = 'bx;

always @ (*) begin
    ap_predicate_op204_read_state1 = ((icmp_ln25_fu_841_p2 == 1'd1) & (tmp_fu_828_p3 == 1'd0));
end

assign firCoeff_address0 = i_cast_fu_836_p1;

assign i_cast_fu_836_p1 = ap_sig_allocacmp_i_1;

assign icmp_ln25_fu_841_p2 = ((ap_sig_allocacmp_i_1 == 9'd0) ? 1'b1 : 1'b0);

assign tmp_fu_828_p3 = ap_sig_allocacmp_i_1[32'd8];

assign trunc_ln29_fu_847_p1 = ap_sig_allocacmp_i_1[7:0];

assign x_TDATA_blk_n = 1'b1;

endmodule //fir_fir_Pipeline_Shift_Accum_Loop
