set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[0]}]

set_property PULLUP true [get_ports {adc_data[13]}]
set_property PULLUP true [get_ports {adc_data[12]}]
set_property PULLUP true [get_ports {adc_data[11]}]
set_property PULLUP true [get_ports {adc_data[10]}]
set_property PULLUP true [get_ports {adc_data[9]}]
set_property PULLUP true [get_ports {adc_data[8]}]
set_property PULLUP true [get_ports {adc_data[7]}]
set_property PULLUP true [get_ports {adc_data[6]}]
set_property PULLUP true [get_ports {adc_data[5]}]
set_property PULLUP true [get_ports {adc_data[4]}]
set_property PULLUP true [get_ports {adc_data[3]}]
set_property PULLUP true [get_ports {adc_data[2]}]
set_property PULLUP true [get_ports {adc_data[1]}]
set_property PULLUP true [get_ports {adc_data[0]}]


set_property PACKAGE_PIN V8 [get_ports {adc_data[13]}]
set_property PACKAGE_PIN V10 [get_ports {adc_data[12]}]
set_property PACKAGE_PIN V9 [get_ports {adc_data[11]}]
set_property PACKAGE_PIN W11 [get_ports {adc_data[10]}]
set_property PACKAGE_PIN W10 [get_ports {adc_data[9]}]
set_property PACKAGE_PIN W12 [get_ports {adc_data[8]}]
set_property PACKAGE_PIN V12 [get_ports {adc_data[7]}]
set_property PACKAGE_PIN AA9 [get_ports {adc_data[6]}]
set_property PACKAGE_PIN AA8 [get_ports {adc_data[5]}]
set_property PACKAGE_PIN Y10 [get_ports {adc_data[4]}]
set_property PACKAGE_PIN AB9 [get_ports {adc_data[3]}]
set_property PACKAGE_PIN AA11 [get_ports {adc_data[2]}]
set_property PACKAGE_PIN AB10 [get_ports {adc_data[1]}]
set_property PACKAGE_PIN Y11 [get_ports {adc_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[0]}]

set_property PULLUP true [get_ports {dac_data[13]}]
set_property PULLUP true [get_ports {dac_data[12]}]
set_property PULLUP true [get_ports {dac_data[11]}]
set_property PULLUP true [get_ports {dac_data[10]}]
set_property PULLUP true [get_ports {dac_data[9]}]
set_property PULLUP true [get_ports {dac_data[8]}]
set_property PULLUP true [get_ports {dac_data[7]}]
set_property PULLUP true [get_ports {dac_data[6]}]
set_property PULLUP true [get_ports {dac_data[5]}]
set_property PULLUP true [get_ports {dac_data[4]}]
set_property PULLUP true [get_ports {dac_data[3]}]
set_property PULLUP true [get_ports {dac_data[2]}]
set_property PULLUP true [get_ports {dac_data[1]}]
set_property PULLUP true [get_ports {dac_data[0]}]


set_property PACKAGE_PIN AB6 [get_ports {dac_data[13]}]
set_property PACKAGE_PIN T6 [get_ports {dac_data[12]}]
set_property PACKAGE_PIN Y4 [get_ports {dac_data[11]}]
set_property PACKAGE_PIN T4 [get_ports {dac_data[10]}]
set_property PACKAGE_PIN AA4 [get_ports {dac_data[9]}]
set_property PACKAGE_PIN U4 [get_ports {dac_data[8]}]
set_property PACKAGE_PIN V7 [get_ports {dac_data[7]}]
set_property PACKAGE_PIN W6 [get_ports {dac_data[6]}]
set_property PACKAGE_PIN W7 [get_ports {dac_data[5]}]
set_property PACKAGE_PIN W5 [get_ports {dac_data[4]}]
set_property PACKAGE_PIN V5 [get_ports {dac_data[3]}]
set_property PACKAGE_PIN U6 [get_ports {dac_data[2]}]
set_property PACKAGE_PIN V4 [get_ports {dac_data[1]}]
set_property PACKAGE_PIN U5 [get_ports {dac_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports adc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]

set_property PACKAGE_PIN AB11 [get_ports adc_clk]
set_property PACKAGE_PIN AB7 [get_ports dac_clk]
set_property PACKAGE_PIN T18 [get_ports reset_rtl]
set_property PACKAGE_PIN Y9 [get_ports sys_clock]

set_property DRIVE 16 [get_ports adc_clk]
set_property DRIVE 16 [get_ports dac_clk]
set_property SLEW FAST [get_ports adc_clk]
set_property SLEW FAST [get_ports dac_clk]



