// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fir,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-3,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.210000,HLS_SYN_LAT=184,HLS_SYN_TPT=185,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6038,HLS_SYN_LUT=2220,HLS_VERSION=2022_2}" *)

module fir (
        y_TDATA,
        x_TDATA,
        ap_clk,
        ap_rst_n,
        x_TVALID,
        x_TREADY,
        ap_start,
        y_TVALID,
        y_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


output  [31:0] y_TDATA;
input  [31:0] x_TDATA;
input   ap_clk;
input   ap_rst_n;
input   x_TVALID;
output   x_TREADY;
input   ap_start;
output   y_TVALID;
input   y_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    Loop_Shift_Accum_Loop_proc2_U0_ap_start;
wire    Loop_Shift_Accum_Loop_proc2_U0_ap_done;
wire    Loop_Shift_Accum_Loop_proc2_U0_ap_continue;
wire    Loop_Shift_Accum_Loop_proc2_U0_ap_idle;
wire    Loop_Shift_Accum_Loop_proc2_U0_ap_ready;
wire    Loop_Shift_Accum_Loop_proc2_U0_x_TREADY;
wire   [31:0] Loop_Shift_Accum_Loop_proc2_U0_ap_return;
wire    acc_loc_channel_full_n;
wire    Block_for_end_proc_U0_ap_start;
wire    Block_for_end_proc_U0_ap_done;
wire    Block_for_end_proc_U0_ap_continue;
wire    Block_for_end_proc_U0_ap_idle;
wire    Block_for_end_proc_U0_ap_ready;
wire   [31:0] Block_for_end_proc_U0_y_TDATA;
wire    Block_for_end_proc_U0_y_TVALID;
wire   [31:0] acc_loc_channel_dout;
wire   [1:0] acc_loc_channel_num_data_valid;
wire   [1:0] acc_loc_channel_fifo_cap;
wire    acc_loc_channel_empty_n;

fir_Loop_Shift_Accum_Loop_proc2 Loop_Shift_Accum_Loop_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_Shift_Accum_Loop_proc2_U0_ap_start),
    .ap_done(Loop_Shift_Accum_Loop_proc2_U0_ap_done),
    .ap_continue(Loop_Shift_Accum_Loop_proc2_U0_ap_continue),
    .ap_idle(Loop_Shift_Accum_Loop_proc2_U0_ap_idle),
    .ap_ready(Loop_Shift_Accum_Loop_proc2_U0_ap_ready),
    .x_TVALID(x_TVALID),
    .x_TDATA(x_TDATA),
    .x_TREADY(Loop_Shift_Accum_Loop_proc2_U0_x_TREADY),
    .ap_return(Loop_Shift_Accum_Loop_proc2_U0_ap_return)
);

fir_Block_for_end_proc Block_for_end_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_for_end_proc_U0_ap_start),
    .ap_done(Block_for_end_proc_U0_ap_done),
    .ap_continue(Block_for_end_proc_U0_ap_continue),
    .ap_idle(Block_for_end_proc_U0_ap_idle),
    .ap_ready(Block_for_end_proc_U0_ap_ready),
    .p_read(acc_loc_channel_dout),
    .y_TDATA(Block_for_end_proc_U0_y_TDATA),
    .y_TVALID(Block_for_end_proc_U0_y_TVALID),
    .y_TREADY(y_TREADY)
);

fir_fifo_w32_d2_S acc_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_Shift_Accum_Loop_proc2_U0_ap_return),
    .if_full_n(acc_loc_channel_full_n),
    .if_write(Loop_Shift_Accum_Loop_proc2_U0_ap_done),
    .if_dout(acc_loc_channel_dout),
    .if_num_data_valid(acc_loc_channel_num_data_valid),
    .if_fifo_cap(acc_loc_channel_fifo_cap),
    .if_empty_n(acc_loc_channel_empty_n),
    .if_read(Block_for_end_proc_U0_ap_ready)
);

assign Block_for_end_proc_U0_ap_continue = 1'b1;

assign Block_for_end_proc_U0_ap_start = acc_loc_channel_empty_n;

assign Loop_Shift_Accum_Loop_proc2_U0_ap_continue = acc_loc_channel_full_n;

assign Loop_Shift_Accum_Loop_proc2_U0_ap_start = ap_start;

assign ap_done = Block_for_end_proc_U0_ap_done;

assign ap_idle = ((1'b1 ^ acc_loc_channel_empty_n) & Loop_Shift_Accum_Loop_proc2_U0_ap_idle & Block_for_end_proc_U0_ap_idle);

assign ap_ready = Loop_Shift_Accum_Loop_proc2_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign x_TREADY = Loop_Shift_Accum_Loop_proc2_U0_x_TREADY;

assign y_TDATA = Block_for_end_proc_U0_y_TDATA;

assign y_TVALID = Block_for_end_proc_U0_y_TVALID;


reg find_kernel_block = 0;
// synthesis translate_off
`include "fir_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //fir

