set_property PACKAGE_PIN AA9 [get_ports dac_sclk]
set_property PACKAGE_PIN AA11 [get_ports dac_mosi_a]
set_property PACKAGE_PIN Y10 [get_ports dac_mosi_b]
set_property PACKAGE_PIN Y11 [get_ports {dac_ss_n[0]}]
set_property PACKAGE_PIN W12 [get_ports {adc_cs_n[0]}]
set_property PACKAGE_PIN W8 [get_ports adc_sck]
set_property PACKAGE_PIN W11 [get_ports adc_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_cs_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_ss_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_data_in]
set_property IOSTANDARD LVCMOS33 [get_ports adc_sck]
set_property IOSTANDARD LVCMOS33 [get_ports dac_mosi_a]
set_property IOSTANDARD LVCMOS33 [get_ports dac_mosi_b]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sclk]

