## pin asignment
set_property PACKAGE_PIN U14 [get_ports {leds[7]}]
set_property PACKAGE_PIN U19 [get_ports {leds[6]}]
set_property PACKAGE_PIN W22 [get_ports {leds[5]}]
set_property PACKAGE_PIN V22 [get_ports {leds[4]}]
set_property PACKAGE_PIN U21 [get_ports {leds[3]}]
set_property PACKAGE_PIN U22 [get_ports {leds[2]}]
set_property PACKAGE_PIN T21 [get_ports {leds[1]}]
set_property PACKAGE_PIN T22 [get_ports {leds[0]}]

set_property PACKAGE_PIN M15 [get_ports {sws[7]}]
set_property PACKAGE_PIN H17 [get_ports {sws[6]}]
set_property PACKAGE_PIN H18 [get_ports {sws[5]}]
set_property PACKAGE_PIN H19 [get_ports {sws[4]}]
set_property PACKAGE_PIN F21 [get_ports {sws[3]}]
set_property PACKAGE_PIN H22 [get_ports {sws[2]}]
set_property PACKAGE_PIN G22 [get_ports {sws[1]}]
set_property PACKAGE_PIN F22 [get_ports {sws[0]}]

## io standard asignment
set_property IOSTANDARD LVCMOS33 [get_ports {sws[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sws[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]

